services:
  chromadb:
    image: docker.io/chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "0.0.0.0:8100:8000"
    volumes:
      - chromadb-data:/chroma/chroma
    environment:
      - ANONYMIZED_TELEMETRY=FALSE
    restart: "no"
    networks:
      - homelab

volumes:
  chromadb-data:

networks:
  homelab:
    external: true
